### ISSUE TITLE
Reset cause

### ISSUE THREAD

**Issue by martincornu** [disk91/stm32-it-sdk#29]
Hi Paul,

It seems that the RCC Control/status register is cleaned at itsdk_setup() so when asking it later in the FW or via NFC console with 'r' command it will always return RESET_CAUSE_UNKNOWN.

Regards,
Martin

**Comment by disk91** [comment]
You right, the reset cause was not stored in the itsdk_state and lost. You were able to access it with the eeprom logs but the 'r' command always returned UNKNONW. This has fixed in the commit https://github.com/disk91/stm32-it-sdk/commit/f19b20a0b0b1609383b66bcdd0ecd064c7482db8
