### ISSUE TITLE
Add new serial speed

### ISSUE THREAD

**Issue by zokl** [disk91/stm32-it-sdk#51]
Hello,

are you able to add new serial line speed to your SDK - 2400, 1200, 900, and 300 bps? There is use full for low-speed devices as power meters or similar. 

Thank you, Zbynek Kocur

**Comment by disk91** [comment]
sure... I'll

**Comment by disk91** [comment]
Have been integrated in devel and master.
Let me know if you have any issue with it.

**Comment by fakub** [comment]
As @zokl outlined, we need bauds 300 and 600, too. Would you please add them as well? Many thanks!

**Comment by disk91** [comment]
Hello, It has been integrated.

**Comment by disk91** [comment]
Added in commit #57
