### ISSUE TITLE
sx126x

### ISSUE THREAD

**Issue by Pascal66** [disk91/stm32-it-sdk#88]
J'ai vu que tu avais intégré le sdk sigfox pour le sx126x dans la branche 'devel'
Je cherche un exemple simple de réception de trames pour jeter un oeil sur le fonctionnement

**Comment by disk91** [comment]
En effet c'est en cours de dev, pour l'instant le code n'est pas terminé et pas testé, ca devrait arriver dans quelques semaines. Je travaille sur le stm32wl qui est un sx126x like mais pas tout à fait, donc je ne garantie pas non plus le 100% fonctionnel sur un sx1262 avant d'avoir pu tester.
